"use client";
import Link from "next/link";
import { Github, Loader2, Mail } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { toast } from "sonner";
import { loginWithEmail, loginWithGithub, loginWithGoogle } from "@/services/auth.service";
const loginSchema = z.object({ email: z.string().min(1, "Informe o e-mail.").email("Informe um e-mail válido."), password: z.string().min(1, "Informe a senha.") });
type LoginFormData = z.infer<typeof loginSchema>;
export function LoginForm() { const router = useRouter(); const [loading,setLoading]=useState(false); const [socialLoading,setSocialLoading]=useState<"google"|"github"|null>(null); const { register, handleSubmit, formState:{errors} } = useForm<LoginFormData>({ resolver: zodResolver(loginSchema) });
async function onSubmit(data: LoginFormData){ try{ setLoading(true); await loginWithEmail(data.email,data.password); toast.success("Login realizado com sucesso!"); router.push("/user"); }catch(error){ console.error(error); toast.error("Não foi possível fazer login. Verifique e-mail e senha."); }finally{ setLoading(false); }}
async function handleGoogleLogin(){ try{ setSocialLoading("google"); await loginWithGoogle(); toast.success("Login com Google realizado com sucesso!"); router.push("/user"); }catch(error){ console.error(error); toast.error("Erro ao entrar com Google."); }finally{ setSocialLoading(null); }}
async function handleGithubLogin(){ try{ setSocialLoading("github"); await loginWithGithub(); toast.success("Login com GitHub realizado com sucesso!"); router.push("/user"); }catch(error){ console.error(error); toast.error("Erro ao entrar com GitHub."); }finally{ setSocialLoading(null); }}
return <div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl"><h1 className="text-3xl font-bold text-slate-950">Entrar no TaskFlow</h1><p className="mt-2 text-slate-600">Acesse sua área protegida para gerenciar suas tarefas.</p><form onSubmit={handleSubmit(onSubmit)} className="mt-8 space-y-4"><div><label className="mb-1 block font-medium text-slate-700" htmlFor="email">E-mail</label><input id="email" type="email" className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none transition focus:border-blue-600" placeholder="seuemail@exemplo.com" {...register("email")}/>{errors.email && <p className="mt-1 text-sm text-red-600">{errors.email.message}</p>}</div><div><label className="mb-1 block font-medium text-slate-700" htmlFor="password">Senha</label><input id="password" type="password" className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none transition focus:border-blue-600" placeholder="Digite sua senha" {...register("password")}/>{errors.password && <p className="mt-1 text-sm text-red-600">{errors.password.message}</p>}</div><button type="submit" disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60">{loading && <Loader2 className="animate-spin" size={18}/>} {loading ? "Entrando..." : "Entrar"}</button></form><div className="my-6 flex items-center gap-3"><div className="h-px flex-1 bg-slate-200"/><span className="text-sm text-slate-500">ou</span><div className="h-px flex-1 bg-slate-200"/></div><div className="space-y-3"><button type="button" onClick={handleGoogleLogin} disabled={socialLoading!==null} className="flex w-full items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-3 font-semibold text-slate-800 transition hover:bg-slate-50 disabled:opacity-60"><Mail size={18}/>{socialLoading === "google" ? "Conectando..." : "Entrar com Google"}</button><button type="button" onClick={handleGithubLogin} disabled={socialLoading!==null} className="flex w-full items-center justify-center gap-2 rounded-xl border border-slate-300 bg-slate-950 px-4 py-3 font-semibold text-white transition hover:bg-slate-800 disabled:opacity-60"><Github size={18}/>{socialLoading === "github" ? "Conectando..." : "Entrar com GitHub"}</button></div><p className="mt-6 text-center text-sm text-slate-600">Ainda não tem conta? <Link href="/register" className="font-semibold text-blue-700 hover:underline">Criar cadastro</Link></p></div>; }
